version: '3.3'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '8929:8929'
      - '2224:22'
    volumes:
      - '${MY_COMPOSE_GITLAB_HOME}/gitlab_data/config:/etc/gitlab'
      - '${MY_COMPOSE_GITLAB_HOME}/gitlab_data/logs:/var/log/gitlab'
      - '${MY_COMPOSE_GITLAB_HOME}/gitlab_data/data:/var/opt/gitlab'
    shm_size: '256m'
  runner:
    image: 'gitlab/gitlab-runner:alpine'
    restart: always
    volumes:
      - '${MY_COMPOSE_GITLAB_HOME}/gitlab_data/runner-config:/etc/gitlab-runner'
      #- './runner.crt:/etc/gitlab-runner/certs/ca.crt:ro'

# GITLAB_OMNIBUS_CONFIG: |
#   external_url 'https://localhost:8929'
#   gitlab_rails['gitlab_shell_ssh_port'] = 2224
#   letsencrypt['contact_emails'] = ['me@example.com']
 
